// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-west-2:fda1c1de-9b2c-41fc-b967-dd8cdf3e309c',
    'aws_cognito_region': 'us-west-2',
    'aws_mobile_analytics_app_id': '1924b2544c4b404eb86a8664bc62a4a8',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '68d6ae6b-d02e-4ab3-b46e-dcef760e7052',
    'aws_project_name': 'Facet',
    'aws_project_region': 'us-west-2',
    'aws_resource_name_prefix': 'facet-mobilehub-1903196492',
}

export default awsmobile;
